/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package janelas;

import conexao.Ranking;
import conexao.Ranking_DAO;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import par_impar.JOGADOR1;
import par_impar.JOGO;
import par_impar.MAQUINA;

/**
 *
 * @author Intel i5
 */
public class Janela_JOGO extends javax.swing.JFrame {

    /**
     * Creates new form Janela_JOGO
     */
    
    public Janela_JOGO(String n){
        j.nome = n;
        initComponents();
    }
    public Janela_JOGO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NUMEROtxt = new javax.swing.JTextField();
        OKbt = new javax.swing.JToggleButton();
        VOLTARbt = new javax.swing.JToggleButton();
        PARIMPARcmb = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        RESUlbl = new javax.swing.JLabel();
        INFORMACAOlbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        VITORIASlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NUMEROtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NUMEROtxtActionPerformed(evt);
            }
        });

        OKbt.setText("OK");
        OKbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKbtActionPerformed(evt);
            }
        });

        VOLTARbt.setText("Voltar");
        VOLTARbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOLTARbtActionPerformed(evt);
            }
        });

        PARIMPARcmb.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        PARIMPARcmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAR", "ÍMPAR" }));
        PARIMPARcmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PARIMPARcmbActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RESUlbl.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        RESUlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RESUlbl.setText("Escolha se é par ou ímpar e o número");
        jPanel1.add(RESUlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, -1));

        INFORMACAOlbl.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        INFORMACAOlbl.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(INFORMACAOlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 260, 20));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel1.setText("Vitórias");

        VITORIASlbl.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        VITORIASlbl.setForeground(new java.awt.Color(255, 0, 0));
        VITORIASlbl.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(OKbt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(VOLTARbt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(NUMEROtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addComponent(PARIMPARcmb, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(VITORIASlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NUMEROtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PARIMPARcmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VITORIASlbl)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VOLTARbt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OKbt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKbtActionPerformed
       
        this.BotãoPrincipal();
    }//GEN-LAST:event_OKbtActionPerformed

    private void VOLTARbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOLTARbtActionPerformed
       this.dispose();
       new Janela_Inicial().setVisible(true);
    }//GEN-LAST:event_VOLTARbtActionPerformed

    private void NUMEROtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NUMEROtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NUMEROtxtActionPerformed

    private void PARIMPARcmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PARIMPARcmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PARIMPARcmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela_JOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela_JOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela_JOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_JOGO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela_JOGO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel INFORMACAOlbl;
    private javax.swing.JTextField NUMEROtxt;
    private javax.swing.JToggleButton OKbt;
    private javax.swing.JComboBox<String> PARIMPARcmb;
    private javax.swing.JLabel RESUlbl;
    private javax.swing.JLabel VITORIASlbl;
    private javax.swing.JToggleButton VOLTARbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   Ranking j = new Ranking();
   Ranking_DAO dao = new Ranking_DAO();
   
   public void BotãoPrincipal(){
       
        JOGO jogo = new JOGO();  
        
        if(NUMEROtxt.getText().length()==0){
          JOptionPane.showMessageDialog(null, "Informe um número!!!", "Informação", WARNING_MESSAGE);
        }else{

        JOGADOR1 jogador = new JOGADOR1(Integer.parseInt(NUMEROtxt.getText()));
        MAQUINA maquina = new MAQUINA();

        jogador.Escolha(PARIMPARcmb.getSelectedIndex());
        maquina.Escolha(PARIMPARcmb.getSelectedIndex());
        jogo.Resultado(jogador.numero, maquina.numero);

        int j1 = jogador.numero;
        int m = maquina.numero;
        int soma = j1 + m;

        if(jogador.par_ou_impar == jogo.resultado){
            RESUlbl.setForeground(Color.BLUE);
            RESUlbl.setText("Você venceu!!");
            
            INFORMACAOlbl.setForeground(Color.BLUE);
            INFORMACAOlbl.setText("A maquina escolheu "+m+", logo "+j1+"+"+m+" = "+soma+" "+jogo.resultado);
            
            j.quantidade_vitoria += 1;
            
            VITORIASlbl.setText(String.valueOf(j.quantidade_vitoria));
            
        }else if(maquina.par_ou_impar == jogo.resultado){
            RESUlbl.setForeground(Color.RED);
            RESUlbl.setText("Você perdeu!!");
        
            INFORMACAOlbl.setForeground(Color.RED);
            INFORMACAOlbl.setText("A maquina escolheu "+m+", logo "+j1+"+"+m+" = "+soma+" "+jogo.resultado);
            
            if(j.quantidade_vitoria > 0){
                int esc = JOptionPane.showConfirmDialog(null, "Deseja salvar a pontuação no nome de "+j.nome+ "?");
                if(esc == 0){
                    
                    j.data = new Date();
                    dao.InserirRanking(j);
                    JOptionPane.showMessageDialog(null, "Pontuação salva com sucesso!!!", "Informação", WARNING_MESSAGE);
                    this.dispose();
                    new Janela_Inicial().setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Ok, voltando para tela inicial...");
                    this.dispose();
                    new Janela_Inicial().setVisible(true);
                }
            }
        }
   }
  }
    
}
